name: unity_video_player_desktop
description: Unity Video Player implementation for Windows, Linux and MacOS
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_vlc: ^0.4.0
  unity_video_player_platform_interface:
    path: ../unity_video_player_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: unity_video_player
    platforms:
      windows:
        dartPluginClass: UnityVideoPlayerDesktopInterface
      linux:
        dartPluginClass: UnityVideoPlayerDesktopInterface
      macos:
        dartPluginClass: UnityVideoPlayerDesktopInterface
