name: unity_video_player_media_kit
description: UnityVideoPlayer implemented using MediaKit
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # We lock the version to a commit because of the inconsistency of the pub cache
  # If an upgrade is necessary, change the [ref] of all packages below to the desired commit
  # Also check the upper package and update any `dependency_overriden` package
  media_kit: 0.0.4
    # git:
    #   url: https://github.com/alexmercerind/media_kit.git
    #   ref: 318f3e157e127af84b70d9907d4b30efd50371e6
    #   path: media_kit/
  media_kit_native_event_loop:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit_native_event_loop/
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit_video/
  media_kit_libs_windows_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit_libs_windows_video/
  media_kit_libs_linux:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit_libs_linux/
  media_kit_libs_macos_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit_libs_macos_video/
  media_kit_libs_android_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit_libs_android_video/
  media_kit_libs_ios_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit_libs_ios_video/
  unity_video_player_platform_interface:
    path: ../unity_video_player_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 318f3e157e127af84b70d9907d4b30efd50371e6
      path: media_kit/

flutter:
  plugin:
    implements: unity_video_player
    platforms:
      windows:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      linux:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      macos:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      ios:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
      android:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
