name: unity_video_player_media_kit
description: UnityVideoPlayer implemented using MediaKit
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # We lock the version to a commit because of the inconsistency of the pub cache
  # If an upgrade is necessary, change the [ref] of all packages below to the desired commit
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: c71d6725dafff4045ed66cd711b10a8f4069bf11
      path: media_kit/
  media_kit_native_event_loop:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: c71d6725dafff4045ed66cd711b10a8f4069bf11
      path: media_kit_native_event_loop/
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: c71d6725dafff4045ed66cd711b10a8f4069bf11
      path: media_kit_video/
  media_kit_libs_windows_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: c71d6725dafff4045ed66cd711b10a8f4069bf11
      path: media_kit_libs_windows_video/
  media_kit_libs_linux:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: c71d6725dafff4045ed66cd711b10a8f4069bf11
      path: media_kit_libs_linux/
  media_kit_libs_macos_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: c71d6725dafff4045ed66cd711b10a8f4069bf11
      path: media_kit_libs_macos_video/
  unity_video_player_platform_interface:
    path: ../unity_video_player_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: unity_video_player
    platforms:
      windows:
        dartPluginClass: UnityVideoPlayerMediaKitInterface
