name: Bluecherry Client Flutter
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_android:
    name: Bluecherry Client Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          cache: true
      # TODO: Signing Android application.
      # - name: Create Key Store
      #   id: create_key_store
      #   uses: timheuer/base64-to-file@v1
      #   with:
      #     fileName: "keystore.pfx"
      #     encodedString: ${{ secrets.KEY_STORE }}
      # - name: Create Key Properties
      #   id: create_key_properties
      #   uses: timheuer/base64-to-file@v1
      #   with:
      #     fileName: "key.properties"
      #     encodedString: ${{ secrets.KEY_PROPERTIES }}
      # - run: cp "${{ steps.create_key_store.outputs.filePath }}" android/app/keystore.jks
      # - run: cp "${{ steps.create_key_properties.outputs.filePath }}" android/key.properties
      - run: flutter gen-l10n
      - run: flutter pub get
      - run: flutter build apk --verbose --split-per-abi
      - run: flutter build appbundle --verbose
      - run: cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk bluecherry-android-arm64-v8a-release.apk
      - run: cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk bluecherry-android-armeabi-v7a-release.apk
      - run: cp build/app/outputs/flutter-apk/app-x86_64-release.apk bluecherry-android-x86_64-release.apk
      - name: Release
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ""
          tag_name: "vnext"
          files: |
            bluecherry-android-arm64-v8a-release.apk
            bluecherry-android-armeabi-v7a-release.apk
            bluecherry-android-x86_64-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}

  build_iOS:
    name: Bluecherry Client iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          architecture: x64
          
      - run: flutter gen-l10n
      - run: flutter pub get
      - run: flutter build ios --verbose --release --no-codesign

      # - name: Release
      #   # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts
      #   if: ${{ github.event_name == 'push' }}
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     prerelease: false
      #     body: ""
      #     tag_name: "vnext"
      #     files: |
      #       bluecherry-dvr-setup.exe
      #     token: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    name: Bluecherry Client Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          cache: true
      - run: flutter gen-l10n
      - run: flutter pub get
      - run: flutter build windows --verbose

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "installer/windows-installer.iss"
        shell: cmd

      - run: cp installer\Output\bluecherry-dvr-setup.exe bluecherry-dvr-setup.exe

      - name: Release
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ""
          tag_name: "vnext"
          files: |
            bluecherry-dvr-setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}

  build_linux:
    name: Bluecherry Client Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev p7zip-full p7zip-rar
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          cache: true
      - run: flutter gen-l10n
      - run: flutter pub get
      - run: flutter build linux --verbose

      # - run: cp /build/linux/x64/release/bundle/bluecherry-dvr-setup.exe bluecherry-dvr-setup.exe

      - name: Release
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ""
          tag_name: "vnext"
          files: |
            bluecherry_linux_x64.7z
          token: ${{ secrets.GITHUB_TOKEN }}
